using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Serialization;

namespace ECU_Framework.Structs
{
    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public struct EcuTableTransform
    {
        public EcuParamTransform cylinders;
        public EcuParamTransform voltages;
        public EcuParamTransform pressures_16;
        public EcuParamTransform pressures_32;
        public EcuParamTransform rotates_16;
        public EcuParamTransform rotates_32;
        public EcuParamTransform idle_rotates;
        public EcuParamTransform throttles_16;
        public EcuParamTransform throttles_32;
        public EcuParamTransform pedals;
        public EcuParamTransform filling_gbc_map;
        public EcuParamTransform filling_gbc_tps;
        public EcuParamTransform throttle_position;
        public EcuParamTransform stop_throttle_position;
        public EcuParamTransform filling_select_koff_tps;
        public EcuParamTransform enrichment_injection_phase;
        public EcuParamTransform enrichment_rate_start_load;
        public EcuParamTransform enrichment_rate_load_derivative;
        public EcuParamTransform enrichment_rate;
        public EcuParamTransform enrichment_sync_amount;
        public EcuParamTransform enrichment_async_amount;
        public EcuParamTransform enrichment_ign_corr;
        public EcuParamTransform enrichment_temp_mult;
        public EcuParamTransform fillings_16;
        public EcuParamTransform fillings_32;
        public EcuParamTransform ignitions;
        public EcuParamTransform ignition_corr_cy;
        public EcuParamTransform injection_corr_cy;
        public EcuParamTransform fuel_mixtures;
        public EcuParamTransform injection_phase;
        public EcuParamTransform ignition_time_rpm_mult;
        public EcuParamTransform ignition_time;
        public EcuParamTransform injector_lag;
        public EcuParamTransform engine_temps;
        public EcuParamTransform air_temps;
        public EcuParamTransform air_temp_mix_corr;
        public EcuParamTransform air_temp_ign_corr;
        public EcuParamTransform engine_temp_mix_corr;
        public EcuParamTransform engine_temp_ign_corr;
        public EcuParamTransform idle_wish_rotates;
        public EcuParamTransform idle_wish_massair;
        public EcuParamTransform idle_wish_ignition;
        public EcuParamTransform idle_wish_ignition_static;
        public EcuParamTransform idle_valve_position;
        public EcuParamTransform idle_throttle_position;
        public EcuParamTransform idle_rpm_pid_act_1;
        public EcuParamTransform idle_rpm_pid_act_2;
        public EcuParamTransform idle_pids_rpm_koffs;
        public EcuParamTransform idle_valve_to_massair_pid_p;
        public EcuParamTransform idle_valve_to_massair_pid_i;
        public EcuParamTransform idle_valve_to_massair_pid_d;
        public EcuParamTransform idle_valve_to_rpm_pid_p;
        public EcuParamTransform idle_valve_to_rpm_pid_i;
        public EcuParamTransform idle_valve_to_rpm_pid_d;
        public EcuParamTransform idle_throttle_to_massair_pid_p;
        public EcuParamTransform idle_throttle_to_massair_pid_i;
        public EcuParamTransform idle_throttle_to_massair_pid_d;
        public EcuParamTransform idle_throttle_to_rpm_pid_p;
        public EcuParamTransform idle_throttle_to_rpm_pid_i;
        public EcuParamTransform idle_throttle_to_rpm_pid_d;
        public EcuParamTransform idle_ign_to_rpm_pid_p;
        public EcuParamTransform idle_ign_to_rpm_pid_i;
        public EcuParamTransform idle_ign_to_rpm_pid_d;
        public EcuParamTransform warmup_mixtures;
        public EcuParamTransform warmup_mix_koffs;
        public EcuParamTransform warmup_mix_corrs;
        public EcuParamTransform cold_start_idle_corrs;
        public EcuParamTransform cold_start_idle_times;
        public EcuParamTransform start_injection_phase;
        public EcuParamTransform start_idle_valve_pos;
        public EcuParamTransform start_throttle_position;
        public EcuParamTransform start_ignition;
        public EcuParamTransform start_tps_corrs;
        public EcuParamTransform start_async_filling;
        public EcuParamTransform start_large_filling;
        public EcuParamTransform start_small_filling;
        public EcuParamTransform start_filling_time;
        public EcuParamTransform idle_rpm_shift_speeds;
        public EcuParamTransform idle_rpm_shift;
        public EcuParamTransform knock_noise_level;
        public EcuParamTransform knock_threshold;
        public EcuParamTransform knock_zone;
        public EcuParamTransform knock_gain;
        public EcuParamTransform knock_filter_frequency;
        public EcuParamTransform knock_cy_level_multiplier;
        public EcuParamTransform tsps_relative_pos;
        public EcuParamTransform tsps_desync_thr;
        public EcuParamTransform idle_ignition_time_by_tps;
        public EcuParamTransform idle_econ_delay;
        public EcuParamTransform start_econ_delay;
        public EcuParamTransform fan_advance_control;
        public EcuParamTransform idle_valve_econ_position;
        public EcuParamTransform idle_throttle_econ_position;
        public EcuParamTransform pedal_ignition_control;
        public EcuParamTransform throttle_position_1d;
        public EcuParamTransform throttle_startup_move_time;
        public EcuParamTransform knock_detect_phase_start;
        public EcuParamTransform knock_detect_phase_end;
        public EcuParamTransform knock_integrator_time;
        public EcuParamTransform enrichment_tps_selection;
        public EcuParamTransform enrichment_accel_dead_band;
        public EcuParamTransform dynamic_fuel_corr_gbc;
        public EcuParamTransform dynamic_fuel_corr_temp;
        public EcuParamTransform dynamic_fuel_corr_lpf;
    }
}
